# Generated by Django 5.2.15 on 2026-07-03 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_period', '0001_initial'),
        ('chart_of_account', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_number', models.CharField(max_length=50, unique=True, verbose_name='Voucher Number')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('bl_number', models.CharField(blank=True, max_length=100, verbose_name='BL Number')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting_period.accountingperiod', verbose_name='Accounting Period')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='vendor.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Journal Voucher',
                'verbose_name_plural': 'Journal Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='chart_of_account.chartofaccount', verbose_name='Account')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal_voucher.journalvoucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['line_order'],
            },
        ),
    ]
